name: Train my model with Pull Request

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  actions: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  run:
    name: Train my model
    runs-on: [ubuntu-latest]
    # container: ghcr.io/iterative/cml:0-dvc3-base1

    steps:
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '17'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v2

      # - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'

      - name: cml
        env:
          REPO_TOKEN: ${{ env.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install -r requirements.txt

          # Pull dataset with DVC
          dvc pull

          # Reproduce pipeline if any changes detected in dependencies
          dvc repro
          ls -l
          echo 'Line 57'
          # git config --global --add safe.directory /__w/course-ds-base-v3/course-ds-base-v3

          # Use DVC metrics diff to compare metrics to main
          git fetch --prune --unshallow
          ls -l
          echo 'Line 62'
          dvc metrics diff --md main >> report.md

          # Add figure to report
          dvc plots diff --target reports/confusion_matrix_data.csv --show-vega main > vega.json
          ls -l
          echo 'Line 79'
          vl2png vega.json -s 1.3 > vega.png
          ls -l
          echo 'Line 72'
          # echo '![](./vega.png)' >> report.md
          ls -l
          echo 'Line 75'
          cml comment create report.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            vega.json
            vega.png
            report.md